[Application Options]

; -------------------------
; Flokicoin options
; -------------------------

[Flokicoin]

; If the Flokicoin chain should be active.
; flokicoin.active=1

; Use Flokicoin's mainnet network.
; flokicoin.mainnet=1

; Use Flokicoin's testnet network.
; flokicoin.testnet=1

; Use Flokicoin's regtest network.
; flokicoin.regtest=1

; Use Flokicoin's signet network.
; flokicoin.signet=1

; Use the flokicoind back-end.
; flokicoin.node=flokicoind

[flokicoind]

; The host:port of the flokicoind RPC server.
; flokicoind.rpchost=localhost

; The username for the flokicoind RPC server.
; flokicoind.rpcuser=user

; The password for the flokicoind RPC server.
; flokicoind.rpcpass=password

; The path to the flokicoind zmq block notification socket.
; flokicoind.zmqpubrawblock=tcp://127.0.0.1:28332

; The path to the flokicoind zmq transaction notification socket.
; flokicoind.zmqpubrawtx=tcp://127.0.0.1:28333

; The estimated time a block takes to be mined.
; flokicoind.estimatemode=CONSERVATIVE

[Protocol]

; If set, then flnd will create and accept requests for wumbo channels, which 
; are channels larger chan 0.16 FLC.
; protocol.wumbo-channels=1

; If set, then flnd will create and accept requests for channels using the 
; simple taproot commitment type.
; protocol.simple-taproot-chans=1

; Disable forwarding of payments that are a part of a blinded route.
; protocol.no-route-blinding=1

; Disable experimental accountability. Experimental accountability was 
; previously known as experimental endorsement.
; protocol.no-experimental-accountability=1

; The deprecated name for no-experimental-accountability.
; protocol.no-experimental-endorsement=1
